# Generated by Django 2.0.1 on 2018-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('external_url', models.URLField()),
                ('discussion_url', models.URLField()),
                ('submitter', models.CharField(max_length=200)),
                ('punctuation', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField()),
                ('number_of_comments', models.IntegerField(default=0)),
            ],
        ),
    ]
