# Generated by Django 2.0.1 on 2018-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('creation_date',)},
        ),
        migrations.AlterField(
            model_name='submission',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
